# Generated by Django 5.2.5 on 2026-06-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
